### ISSUE TITLE
アラートが表示されたあと、ブラウザ上でエラー。

### ISSUE THREAD

**Issue by koh97222** [koh97222/react-todos#2]
【エラー抜粋】
index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at Transition (http://localhost:3000/static/js/0.chunk.js:95756:30)
    at Collapse (http://localhost:3000/static/js/0.chunk.js:6865:24)
    at WithStyles(ForwardRef(Collapse)) (http://localhost:3000/static/js/0.chunk.js:52034:31)
    at div
    at Grid (http://localhost:3000/static/js/0.chunk.js:11839:35)
    at WithStyles(ForwardRef(Grid)) (http://localhost:3000/static/js/0.chunk.js:52034:31)
    at div
    at Grid (http://localhost:3000/static/js/0.chunk.js:11839:35)
    at WithStyles(ForwardRef(Grid)) (http://localhost:3000/static/js/0.chunk.js:52034:31)
    at TodoPage (http://localhost:3000/static/js/main.chunk.js:1110:19)
    at div
    at div
    at Container (http://localhost:3000/static/js/0.chunk.js:7238:23)
    at WithStyles(ForwardRef(Container)) (http://localhost:3000/static/js/0.chunk.js:52034:31)
    at App
console.<computed> @ index.js:1

**Comment by koh97222** [comment]
findDOMNode()の説明。
DOM にこのコンポーネントがマウントされている場合、このメソッドは対応するネイティブブラウザの DOM 要素を返します。このメソッドはフォームフィールドの値や DOM の大きさを計測するのに便利です。ほとんどのケースにおいて、DOM ノードに ref をアタッチすることで findDOMNode の使用を避けることができます。
→useRef()を用いて、呼び出し先のDOMノードにrefをアタッチすることで、findDOMNode の使用を避けられる？

**Comment by koh97222** [comment]
Collapseコンポーネントは内部でTransition、divタグをラップしているが、そのコンポーネントに参照が渡すことができなかったが、ThemeProviderタグを用意し、そのthemeにunstable_createMuiStrictModeTheme()をセットしてあげることで、エラーを回避した。

https://stackoverflow.com/questions/62250315/warning-about-deprecated-finddomnode-when-using-react-router-navigation-prompt

【Document抜粋】
Requirements
Using unstable_createMuiStrictModeTheme restricts the usage of some of our components.

component prop
The component used in the component prop of the following components need to forward their ref:

Collapse
Otherwise you'll encounter Error: Function component cannot be given refs. See also: Composition: Caveat with refs.

children prop
The children of the following components need to forward their ref:

Fade
Grow
Zoom

https://material-ui.com/customization/theming/
